### ISSUE TITLE
Aint working on my Arch Kde Wm

### ISSUE THREAD

**Issue by divija027** [re1san/Kde-Dots#10]
So as you said first i installed this script on terminal (  source <(curl -s https://raw.githubusercontent.com/re1san/Kde-Dots/main/install.sh) , then i went to settings to change 
    Application Style to Lightly
    Window Deco to Nitrux
    Fonts > Adjust all fonts to Lexend & Fix-width font to Iosevka Nerd Font
    Icons to Reversal-black-dark
But here i cant find any of those above mentioned styles like lighty,nitrux and soo ..

**Comment by re1san** [comment]
Hi did other stuff got installed?

**Comment by divija027** [comment]
no none of them worked for me (:

**Comment by re1san** [comment]
Did you get any error while installing?

**Comment by divija027** [comment]
![errorpointsarch](https://github.com/re1san/Kde-Dots/assets/120162688/623c2ec9-2364-4f6f-adac-9d52ae7dbddc)

**Comment by re1san** [comment]
Ah its the issue with ISP, you can follow this article to fix it: https://www.google.com/amp/s/www.debugpoint.com/failed-connect-raw-githubusercontent-com-port-443/%3famp=1

**Comment by divija027** [comment]
Yea mate the problem was with isp , after adding up vpn i was able to install script, but even after installing script somethings work and some don't . So i req you to do a simple yt vedio of the complete process. Thank You for your time :)

**Comment by re1san** [comment]
Hmm, sure I will do it maybe in few days
